apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointless
  labels:
    app: pointless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointless
  template:
    metadata:
      labels:
        app: pointless
    spec:
      containers:
      - name: pointless
        image: marci/pointless:sha-abcba0e
        ports:
          - containerPort: 3000
        env:
        - name: ENV
          value: prod