name: 'Build docker image'
description: 'Build docker image & push to registry'
inputs:
  dockerhub_username:
    description: docker username
    default: ''
    required: true
  dockerhub_password:
    description: docker password
    default: ''
    required: true
  token:
    description: github token
    default: ''
    required: true
runs:
  using: 'composite'
  # based on https://github.com/marketplace/actions/build-and-push-docker-images
  steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.dockerhub_username }}/pointless
        tags: |
          type=sha
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}
    - name: Github sha
      run: echo "SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      shell: bash
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        