name: 'Unit test'
description: 'Run unit test & lint for pointless project'
inputs:
  token:
    description: github token
    default: ''
    required: true
runs:
  using: 'composite'
  steps:
    - run: cargo test
      shell: bash
    - name: Install clippy
      run: rustup component add clippy
      shell: bash
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ inputs.token }}
        args: --all-features