on:
  push:
    branches:
     - dev

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./action_run_test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./action_docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }} 
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}
  
  deploy:
    needs: [test, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: update gogo helm chart
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`"
          body=$(cat << EOF
          {
            "ref": "main",
            "inputs": {
              "environment": "preproduction",
              "tag": "sha-$SHORT_SHA"
            }
          }
          EOF
          )

          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PROJECT_TOKEN" \
            https://api.github.com/repos/shigedangao/gogo/actions/workflows/dispatch.yaml/dispatches \
            -d "$body"
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
