on:
  push:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./action_run_test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  