on:
  push:
    branches:
     - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./action_run_test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./action_docker
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }} 
          dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          commit_hash: $(git rev-parse --short "$GITHUB_SHA")
          token: ${{ secrets.GITHUB_TOKEN }}